spring:
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 500MB
  redis:
    database: 1
    host: 110.40.181.16
    port: 6379
    password: S62tcFeZ$
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-01kd8mye.sql.tencentcdb.com:27867/web_curriculum_design?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false
    username: root
    password: 0nlinData
  mail:
    host: smtp.qq.com
    username: 1362711574@qq.com
    password: imlivaixfltuijdj
    defaultEncoding: utf-8
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
        mine:
          splitlongparameters: flase
  thymeleaf:
    prefix: classpath:./src/main/resources/templates/

#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.sduonline.timecapsule.util.ListStringTypeHandler

server:
  port: 8040
